workflows:
  android-build:
    name: Kutak Launcher APK

    environment:
      android_signing:
        - Timur
      vars:
        CM_KEYSTORE_PASSWORD: $CM_KEYSTORE_PASSWORD
        CM_KEY_ALIAS: $CM_KEY_ALIAS
        CM_KEY_PASSWORD: $CM_KEY_PASSWORD

    scripts:
      - chmod +x gradlew
      - ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
