plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.kutak.launcher'

    compileSdk 35

    defaultConfig {
        applicationId 'ru.kutak.launcher'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("keystore.jks")
            storePassword "android"
            keyAlias "android"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}
